[package]
org = "ballerina"
name = "soap"
version = "0.2.0"
authors = ["Ballerina"]
export=["soap.soap11", "soap.soap12"]
keywords = ["soap"]
repository = "https://github.com/ballerina-platform/module-ballerina-soap"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/soap-native-0.0.1-SNAPSHOT.jar"

[[platform.java17.dependency]]
path = "./lib/wss4j-ws-security-dom-3.0.1.jar"

[[platform.java17.dependency]]
path = "./lib/wss4j-ws-security-common-3.0.1.jar"

[[platform.java17.dependency]]
groupId = "org.apache.santuario"
artifactId = "xmlsec"
version = "3.0.2"
path = "./lib/xmlsec-3.0.2.jar"
