[package]
org = "ballerina"
name = "soap"
version = "0.2.0"
authors = ["Ballerina"]
export=["soap", "soap.soap11", "soap.soap12"]
keywords = ["soap"]
repository = "https://github.com/ballerina-platform/module-ballerina-soap"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "soap-native"
version = "0.2.0-SNAPSHOT"
path = "../native/build/libs/soap-native-0.2.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "org.apache.wss4j"
artifactId = "wss4j-ws-security-dom"
version = "@wsSecurityDomVersion@"
path = "./lib/wss4j-ws-security-dom-@wsSecurityDomVersion@.jar"

[[platform.java17.dependency]]
groupId = "org.apache.wss4j"
artifactId = "wss4j-ws-security-common"
version = "@wsSecurityCommonVersion@"
path = "./lib/wss4j-ws-security-common-@wsSecurityCommonVersion@.jar"

[[platform.java17.dependency]]
groupId = "org.apache.santuario"
artifactId = "xmlsec"
version = "@xmlSecVersion@"
path = "./lib/xmlsec-@xmlSecVersion@.jar"
